[32mINFO    [0m Test_007_Product_Display:test_product_display.py:211 ************************* Test Product Display 005 is Start *************************
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:213 Navigating to the base url
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:216 Entering iMac product to the search text box field
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:218 Clicking on the search icon button
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:221 Clicking on the product display in the search result
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:222 ************************* Verifying Test Product Display 005 *************************
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:227 Updating quantity by 3
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:229 Clicking on add to cart button
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:232 Clicking on the shopping cart link
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:236 ************** Test Product Display 005 is Passed **************
[32mINFO    [0m Test_007_Product_Display:test_product_display.py:253 ************************* End Of Test Product Display 005 *************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001977F8379B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2c87f5a4d537c2f7d97725ad09b8250f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001977F837CE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2c87f5a4d537c2f7d97725ad09b8250f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001977FD3C050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2c87f5a4d537c2f7d97725ad09b8250f