[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:647 ***************************** Test Product Compare 017 is Start ***************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:649 Navigating to the base url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:652 Entering iMac product to the search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:654 Clicking on the search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:657 Clicking on the compare this option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:659 Entering iMac product to the search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:661 Clicking on the search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:663 Clicking on the compare this option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:665 Entering iMac product to the search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:667 Clicking on the search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:669 Clicking on the compare this option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:671 Clicking on the product comparison link
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:672 ***************************** Verifying Test Product Compare 017 ***************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:696 ********* Test Product Compare 017 is Passed *********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:712 *************************** End Test Product Compare 017 *****************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D584DB020>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/41f6d75a61597f11b81f476642d8af16
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D584DACF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/41f6d75a61597f11b81f476642d8af16
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D584DA470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/41f6d75a61597f11b81f476642d8af16