[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:1018 ************************** Test Product Compare 023 is Start *************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:1020 Navigating to the base url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:1023 Entering iMac product to the search box field 
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:1025 Clicking on the search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:1031 clicking on compare this product option available on the Product that is displayed in the Search result
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:1035 clicking on product comparison link
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:1038 *********** Test Product Compare 023 is Passed ***********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:1050 ********************* End Test Product Compare 023 *************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:1052 ************************** Verifying Test Product Compare 023 *************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BBC7F0D7B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/928ef962f85bf5f84d4cefdf447cb08d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BBC7F0E690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/928ef962f85bf5f84d4cefdf447cb08d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BBC7F0E580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/928ef962f85bf5f84d4cefdf447cb08d