[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:525 *************************** Test Product Compare 015 is Start *****************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:527 Navigating to the base url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:530 Entering iMac product to the search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:532 Clicking on the search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:535 Clicking on compare this product option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:537 Entering iphone product to the search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:539 Clicking on the search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:541 Clicking on compare this product option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:543 Clicking on the product comparison link
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:545 ************************ Verifying Test Product Compare 015 ************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:568 ********* Test Product Compare 015 is Passed *********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:579 *************************** End Test Product Compare 015 *****************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000194B1457570>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5c8c0849583aaab9c02053dd059270a7
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000194B14578A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5c8c0849583aaab9c02053dd059270a7
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000194B1457BD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5c8c0849583aaab9c02053dd059270a7