[32mINFO    [0m Test_005_Search_Functionality:test_search.py:73 **************** Test Search Functionality 003 Started ******************
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:75 Navigating to the URL
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:78 Clicking on search button
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:79 *********** Verifying Test Search functionality 003 ************
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:84 ********** Test Search Functionality 003 is Passed ***********
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:89 ***************** End Of Test Search Functionality 003 ******************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F36DAA7680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aeb265e4e9e089874013b98f2a6ddec2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F36DC2D9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aeb265e4e9e089874013b98f2a6ddec2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F36DC2E690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aeb265e4e9e089874013b98f2a6ddec2