[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:139 ***************** Test Product Compare 004 Is Start *****************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:141 Navigating to the url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:145 hovering on desktops option and clicking on show all desktops option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:147 Clicking on list view button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:148 *************** Verifying Test Product Compare 004 ****************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:153 clicking on compare this product option available on the Product that is displayed in the Product Category page
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:157 clicking on product comparison link
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:160 *********** Test Product Compare 004 is Passed ***********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:174 ********************* End Test Product Compare 004 *************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019135DB3BD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d7acb1345133e13e380b05130c4c5e1a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019135DB3F00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d7acb1345133e13e380b05130c4c5e1a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001913601C270>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d7acb1345133e13e380b05130c4c5e1a