[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:526 *************************** Test Product Compare 015 is Start *****************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:528 Navigating to the base url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:531 Entering iMac product to the search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:533 Clicking on the search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:536 Clicking on compare this product option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:538 Entering iphone product to the search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:540 Clicking on the search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:542 Clicking on compare this product option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:544 Clicking on the product comparison link
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:546 ************************ Verifying Test Product Compare 015 ************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:569 ********* Test Product Compare 015 is Passed *********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:580 *************************** End Test Product Compare 015 *****************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C51E4D260>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/702f5c428bec1531ccd9d68bdf3aaa34
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C51E4DAE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/702f5c428bec1531ccd9d68bdf3aaa34
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C51E4C5A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/702f5c428bec1531ccd9d68bdf3aaa34