[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:99 ***************** Test Product Compare 003 Is Start *****************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:101 Navigating to the url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:104 Entering iMac product for search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:106 clicking on search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:109 Clicking on grid view button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:110 *************** Verifying Test Product Compare 003 ****************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:115 clicking on compare this product option available on the Product that is displayed in the Search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:118 clicking on product comparison link
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:122 *********** Test Product Compare 003 is Passed ***********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:134 ********************* End Test Product Compare 003 *************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000249CA7F1370>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/81e9e158889aa8ebbb74cab2de8f0c4a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000249CA7F0D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/81e9e158889aa8ebbb74cab2de8f0c4a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000249CA7F2CF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/81e9e158889aa8ebbb74cab2de8f0c4a