[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:224 ****************** Test Product Compare 006 Is Starting *********************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:226 Navigating to base url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:229 Entering iMac product to search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:231 Clicking on search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:234 Click on the iMac Product displayed in the Search results 
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:235 *************** Verifying Test Product Compare 006 ****************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:240 clicking on compare this product option available on the Product that is displayed in the Product Category page
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:244 clicking on product comparison link
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:247 *********** Test Product Compare 006 is Passed ***********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:261 ********************* End Test Product Compare 006 *************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DEAA2BDAE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/caacb47e647e50e8d5da474b51ff4f67
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DEAA2BDE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/caacb47e647e50e8d5da474b51ff4f67
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DEAA2BE140>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/caacb47e647e50e8d5da474b51ff4f67