[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:59 ***************** Test Product Compare 002 Is Start *****************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:61 Navigating to the url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:64 Entering iMac product for search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:66 clicking on search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:69 Clicking on list view button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:70 *************** Verifying Test Product Compare 002 ****************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:76 clicking on compare this product option available on the Product that is displayed in the Search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:79 clicking on product comparison link
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:85 *********** Test Product Compare 002 is Passed ***********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:97 ********************* End Test Product Compare 002 *************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000143AE475150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/20e640de19dc2029114e61af503a8d03
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000143C4DCEE00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/20e640de19dc2029114e61af503a8d03
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000143C4DCFAC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/20e640de19dc2029114e61af503a8d03