[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:221 ****************** Test Product Compare 006 Is Starting *********************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:223 Navigating to base url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:226 Entering iMac product to search
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:228 Clicking on search button
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:231 Click on the iMac Product displayed in the Search results 
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:232 *************** Verifying Test Product Compare 006 ****************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:237 clicking on compare this product option available on the Product that is displayed in the Product Category page
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:241 clicking on product comparison link
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:244 *********** Test Product Compare 006 is Passed ***********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:258 ********************* End Test Product Compare 006 *************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025B0DC2EF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/02d98708353bac17f024447b66231479
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025B0DC2F240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/02d98708353bac17f024447b66231479
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025B0DC2F570>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/02d98708353bac17f024447b66231479